@echo off
cd customer_purchase_ai
echo Setting up Python Virtual Environment...
py -m venv venv
call venv\Scripts\activate.bat
echo Installing Dependencies...
pip install -r backend\requirements.txt
echo Generating Mock Dataset...
py ml\generate_dummy_data.py
echo Initializing Training Pipeline...
py ml\train_model.py
echo Starting FastAPI Backend...
uvicorn backend.main:app --host 0.0.0.0 --port 5050 --reload
