from fastapi import FastAPI, HTTPException, UploadFile, File
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse
from pydantic import BaseModel
import sys
import os
import json
import shutil

# Add parent directory to path to import ml module
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from ml.train_model import train_pipeline
from ml.predict import predict_purchase

app = FastAPI(title="AI Customer Purchase Predictor Integration")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class CustomerData(BaseModel):
    age: int
    income: float
    website_visits: int
    past_purchases: int
    days_since_last_purchase: int

# ----- API ROUTES -----

@app.post("/api/upload")
async def upload_dataset(file: UploadFile = File(...)):
    try:
        data_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "../data"))
        os.makedirs(data_dir, exist_ok=True)
        file_location = os.path.join(data_dir, "hackathon_dataset.csv")
        
        # Overwrite the master dataset with the user's fresh upload!
        with open(file_location, "wb+") as file_object:
            shutil.copyfileobj(file.file, file_object)
            
        return {"info": f"Dataset '{file.filename}' uploaded securely. You may now hit Train!"}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to save upload: {str(e)}")

@app.post("/api/train")
def train_model_endpoint():
    try:
        metrics = train_pipeline()
        if not metrics:
            return {"error": "Training failed or data missing. Did you upload a CSV first?"}
        return {"message": "Model trained successfully!", "metrics": metrics}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/api/predict")
def predict_endpoint(data: CustomerData):
    try:
        prediction, probability = predict_purchase(data.dict())
        return {
            "prediction": prediction,
            "probability": round(probability, 2)
        }
    except FileNotFoundError:
        raise HTTPException(status_code=400, detail="Models not trained yet. Please call /api/train first.")
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/api/metrics")
def get_metrics():
    try:
        with open('../reports/best_metrics.json', 'r') as f:
            metrics = json.load(f)
        return metrics
    except FileNotFoundError:
        raise HTTPException(status_code=404, detail="Metrics not found. Train model first.")


# ----- STATIC FILE MOUNTS (REPORTS & REACT UI) -----

reports_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "../reports"))
if not os.path.exists(reports_dir):
    os.makedirs(reports_dir)
# Serve the generated matplotlib PNGs directly so the React App can load them!
app.mount("/api/reports", StaticFiles(directory=reports_dir), name="reports")

frontend_dist = os.path.abspath(os.path.join(os.path.dirname(__file__), "../frontend/dist"))
frontend_assets = os.path.join(frontend_dist, "assets")

if os.path.exists(frontend_assets):
    # Mount the /assets directory generated by React/Vite
    app.mount("/assets", StaticFiles(directory=frontend_assets), name="assets")

@app.get("/")
def serve_frontend():
    index_path = os.path.join(frontend_dist, "index.html")
    if not os.path.exists(index_path):
        return {"error": "Frontend build not found. Please compile Vite React via run_fullstack.bat."}
    return FileResponse(index_path)

@app.get("/{full_path:path}")
def serve_react(full_path: str):
    # Ignore API calls, let them catch 404 natively
    if full_path.startswith("api/"):
        raise HTTPException(status_code=404, detail="API route not found.")
        
    index_path = os.path.join(frontend_dist, "index.html")
    if os.path.exists(index_path):
        return FileResponse(index_path)
    return {"error": "Frontend build not found."}
